// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AreolineaAPI.Models;

public partial class Aeropuertos
{
    [Key]
    public int ID_Aeropuerto { get; set; }

    [StringLength(80)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [StringLength(80)]
    [Unicode(false)]
    public string Ciudad { get; set; }

    [StringLength(80)]
    [Unicode(false)]
    public string Estado { get; set; }

    [StringLength(80)]
    [Unicode(false)]
    public string Pais { get; set; }

    [InverseProperty("Destino")]
    public virtual ICollection<Rutas> RutasDestino { get; set; } = new List<Rutas>();

    [InverseProperty("Origen")]
    public virtual ICollection<Rutas> RutasOrigen { get; set; } = new List<Rutas>();
}