// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AreolineaAPI.Models;

public partial class Rutas
{
    [Key]
    public int ID_Ruta { get; set; }

    public int? Origen_ID { get; set; }

    public int? Destino_ID { get; set; }

    public double? Tiempo_Vuelo { get; set; }

    [ForeignKey("Destino_ID")]
    [InverseProperty("RutasDestino")]
    public virtual Aeropuertos Destino { get; set; }

    [ForeignKey("Origen_ID")]
    [InverseProperty("RutasOrigen")]
    public virtual Aeropuertos Origen { get; set; }

    [InverseProperty("Ruta")]
    public virtual ICollection<Vuelos> Vuelos { get; set; } = new List<Vuelos>();
}